# Generated by Django 2.2 on 2020-04-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quran',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('databaseid', models.SmallIntegerField(db_column='DatabaseID')),
                ('suraid', models.IntegerField(db_column='SuraID')),
                ('verseid', models.IntegerField(db_column='VerseID')),
                ('ayahtext', models.TextField(db_column='AyahText')),
            ],
            options={
                'db_table': 'Quran',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuranPersianElaheqomsheei',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('databaseid', models.SmallIntegerField(db_column='DatabaseID')),
                ('suraid', models.IntegerField(db_column='SuraID')),
                ('verseid', models.IntegerField(db_column='VerseID')),
                ('ayahtext', models.TextField(db_column='AyahText')),
            ],
            options={
                'db_table': 'Quran_persian_elaheqomsheei',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuranSuraNames',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Sura Name', verbose_name='Name')),
                ('place_of_revelation', models.TextField(choices=[('مکه', 'مکه'), ('مدینه', 'مدینه')], help_text='Place of revelation', verbose_name='Place_of_Revelation')),
            ],
            options={
                'verbose_name': 'Sura Name',
                'verbose_name_plural': 'Sura Names',
                'db_table': 'Quran_sura_name_farsi',
            },
        ),
    ]
